# Generated by Django 5.0 on 2023-12-09 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('Todo', 'Todo'), ('done', 'Done')], default='Todo', max_length=10),
        ),
    ]
